# Basic
title: FC烂笔头
subtitle: Changer119
description: 记录点滴，回味生活，day day up...

# 头像里面的标题
avatarTitle: FCabc
# 头像里面的描述
avatarDesc: 编程·管理·运动·读书
url: "http://changer119.github.io"

# Comment
comment:
    # disqus: leopard
    duoshuo: changer119 

# Social
social:
    wechat: fachangjiang 
    github: changer119
    mail: jiangfachang@gmail.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 15c4fed56d4cae267af95752c20fa16effffffffffffff  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-87578654-1-fffff
    host: auto  


# ----------------- 上面的信息修改成你自己的 ---------------------------
#
#  _post/   文章目录
#  _drafts/ 未发布的文章目录
#  目录结构具体参考文档：http://jekyll.com.cn/docs/structure/
#
# --------------- 下面的信息可以自行选择是否修改 ------------------------


permalink: /:year/:month/:title/
# Format
markdown: kramdown
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear #背景Mask

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 存档, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于, description: about, url: '/about'}      
    

# Pagination
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


